[package.metadata.xtask]
project = "p3"
part = "rp"
target = "thumbv6m-none-eabi"
chip = "RP2040"
order = 0

[package]
name = "p3"
edition.workspace = true
version.workspace = true

[dependencies]
embassy-executor = { workspace = true }
embassy-time = { workspace = true }
embassy-futures = { workspace = true }
embassy-usb = { version = "0.6.0" }
static_cell = { workspace = true }
portable-atomic = { version = "1", features = ["critical-section"] }
panic-halt = { workspace = true }
fixed = { workspace = true }

cortex-m = { version = "0.7.9", features = ["inline-asm"] }
cortex-m-rt = "0.7.6"
embassy-rp = {
  version = "0.10.0",
  features = [
    "rp2040",
    "time-driver",
    "executor-thread",
    "critical-section-impl",
    "executor-interrupt",
  ],
}
embedded-graphics = "0.8.2"
ssd1306 = { version = "0.10.0", features = [ "async" ] }
