[workspace]
resolver = "3"
members = [
  "rp2040",
  "esp32c3",
  "shared",
]

[workspace.dependencies]
embassy-executor = { version = "0.10.0" }
embassy-time = { version = "0.5.1" }
embassy-futures = { version = "0.1.2" }
embassy-net = { version = "0.9.1", features = [
  "dhcpv4",
  "tcp",
  "udp"
] }
defmt = { version = "1.1.1" }
static_cell = { version = "2.1.1" }
panic-halt = { version = "1.0.0" }
