[alias]
xtask = "run --quiet --package xtask --"

[target.thumbv6m-none-eabi]
runner = "sudo picotool load -v -x -t elf"
rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tlink-rp.x",
]

[target.riscv32imc-unknown-none-elf]
runner = "sudo espflash flash --monitor --log-format defmt"
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  "-C", "link-arg=-Tdefmt.x",
  "-C", "force-frame-pointers",
]
