[target.thumbv6m-none-eabi]
rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tlink-rp.x",
]

[target.riscv32imc-unknown-none-elf]
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  "-C", "force-frame-pointers",
]
